version: "3.8"

services:
  jotihunt-notifier:
    image: ghcr.io/scoutingscherpenzeel/jotihunt-telegram-notifier:latest
    environment:
      - DISCORD_BOT_TOKEN=
      - DISCORD_CHANNEL_ID=
    volumes:
      - ./sent_articles.json:/app/sent_articles.json
    restart: unless-stopped # Automatically restart the bot unless it is stopped manually
